### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by mouyuemoyu** [xiaojie0202/IDC_Manage#1]
[root@cloud IDC_Manage]# python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/python3/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/python3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/python3/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.6/site-packages/xadmin/__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "/usr/local/python3/lib/python3.6/site-packages/xadmin/sites.py", line 9, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by xiaojie0202** [comment]
django版本号是什么？

**Comment by xiaojie0202** [comment]
你这个问题是xadmin的原因，https://github.com/sshwsfc/xadmin 安装这个版本就行了
